### ISSUE TITLE
telephone-line-accent-* face won't show propertized strings correctly

### ISSUE THREAD

**Issue by shackra** [dbordak/telephone-line#67]
I've been debugging this for a while thinking this is fault of [all-the-icons package](https://github.com/domtronn/all-the-icons.el), but by accident I found that `accent` face won't respect propertized strings, in the following screenshot you can see something like a cloud and at its right an exclamation mark, the icons are supposed to be the same --an exclamation mark inside a circle-- but on the `accent` "side" the character is not rendered propertly using the FontAwesome font, take a look:

![captura de pantalla de 2018-04-14 17-51-11](https://user-images.githubusercontent.com/1055216/38773575-2344df04-400d-11e8-89dc-9a55ccf952fc.png)

Since in the source code `accent` is composed of two faces that inherits from the `mode-line` face we should see improperly shown characters on the mode-line *sans* telephone-line-mode, right? wrong!:

![captura de pantalla de 2018-04-14 18-00-57](https://user-images.githubusercontent.com/1055216/38773600-cd8d00b8-400d-11e8-83b5-ab9958f63840.png)

The check inside a circle, the exclamation mark inside a red-ish triangle and the Git inside a square are shown perfectly.

This is what `describe-face RET mode-line RET` shows for my Emacs configuration:

```
Face: mode-line (sample) (customize this face)

Documentation:
Basic mode line face for selected window.

Defined in ‘faces.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #F8F8F0
DistantForeground: unspecified
       Background: #49483E
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: nil
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```
